[phases.setup]
nixPkgs = ["dotnet-sdk_10"]

[phases.build]
cmds = ["dotnet restore FunctionPointAPI.csproj", "dotnet publish FunctionPointAPI.csproj -c Release -o out"]

[start]
cmd = "dotnet out/FunctionPointAPI.dll"